### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by nnZidan** [bourdakos1/CapsNet-Visualization#5]
Versions of many libraries have gone ahead and do not support the old format of communication among themselves. It turned out to start only after I picked up the correct libraries

bleach==1.5.0
click>=6.7
cycler>=0.10.0
enum34>=1.1.6
Flask==0.12.2
html5lib==0.9999999
itsdangerous>=0.24
Jinja2>=2.10
Markdown>=2.6.11
MarkupSafe>=1.0
matplotlib>=2.1.2
numpy>=1.14.0
Pillow>=5.0.0
protobuf>=3.5.1
pyparsing>=2.2.0
python-dateutil>=2.6.1
pytz>=2017.3
scipy>=1.0.0
six>=1.11.0
tensorflow>=1.4.1
tensorflow-tensorboard>=0.4.0
Werkzeug>=0.14.1

**Comment by bourdakos1** [comment]
I don't actively maintain this project anymore, but I'd be happy to merge any pull requests

**Comment by bourdakos1** [comment]
all versions bumped, thanks @pnbrown 🎉
